### ISSUE TITLE
Unable to change environment (most likely user error)

### ISSUE THREAD

**Issue by neophiliacNoob** [refractionPOINT/python-limacharlie#1]
While using CLI, i am unable to change environments. 

❯ limacharlie
❯ . <(limacharlie use test)
/dev/fd/18:1: command not found: Current
/dev/fd/18:3: command not found: Available
/dev/fd/18:4: command not found: test1
/dev/fd/18:5: command not found: test
/dev/fd/18:7: no such file or directory: environment_name
❯ limacharlie use test
Current environment: default

Available environments:
test1
test

limacharlie use <environment_name> to change environment

**Comment by maximelb** [comment]
Good catch, replicated. It was introduced in our recent major refactor of the CLI.

Fix inbound.

**Comment by maximelb** [comment]
Pushed to `pip` as version 3.4.1, should be available in a minute.
