### ISSUE TITLE
Lima Charlie Manager fails to load environment

### ISSUE THREAD

**Issue by priamai** [refractionPOINT/python-limacharlie#30]
## Expected Behavior

```
import limacharlie

# Create an instance of the SDK.
man = limacharlie.Manager()
```

Should produce no errors

## Actual Behavior

The LC manager is unable to find the settings.
```
((ava) ) ava@lcservice:~/nanocyber$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    man = limacharlie.Manager()
  File "/home/ava/.local/share/virtualenvs/ava-glJNHu3-/lib/python3.8/site-packages/limacharlie/Manager.py", line 85, in __init__
    raise LcApiException( 'LimaCharlie "default" environment not set, please use "limacharlie login".' )
limacharlie.utils.LcApiException: LimaCharlie "default" environment not set, please use "limacharlie login".
```

## Steps to Reproduce the Problem

  1. Installed python3
  2. Installed pipenv
  3. Activated local shell
  4. Installed limcharlie via pip
  5. Performed limacharlie login
  6. File .lcservice is correctly populated on home folder
  7. Performed limacharlive environment
  8. Selected the only one called nanocyber
  9. Run script python test.py

## Specifications

  - Version: Python 3
  - Platform: Ubuntu

**Comment by maximelb** [comment]
This error is indicating that you're not logged in to the SDK. You can either provide a OID and API Key to the Manager() instance, or login with "limacharlie login" to set a default environnement. (If you look at the exception message at the bottom this is where it's stated).

**Comment by maximelb** [comment]
Oh sorry just saw the login in the repro steps.

**Comment by maximelb** [comment]
The root issue is simple: it cannot find the file.

I have not used virtual env in a long time, is it possible that the virtual env is also changing your home directory from within the python?

**Comment by robomotic** [comment]
Gosh that would be possible let me investigate.
Is there a way to force the LC manager to load the .env file from a specific path?

**Comment by priamai** [comment]
So I tried this:

```
import limacharlie
import os

from pathlib import Path
print('LC file is in /home/ava/.limacharlie')
print('Path home %s ' % Path.home())
print('Path expand %s ' % os.path.expanduser("~"))
# Create an instance of the SDK.
man = limacharlie.Manager()
```

To see whether pipenv mask the real home path but it seems not:

```
LC file is in /home/ava/.limacharlie
Path home /home/ava 
Path expand /home/ava 
```
I think it would be useful for the constructor to also provide an argument to load the limacharlie file from a specific path?

**Comment by maximelb** [comment]
Sorry for the delay, did not get a notification from replies here.

Looks like it is possible to customize the file locations by setting the `LC_CREDS_FILE` environment variable: https://github.com/refractionPOINT/python-limacharlie/blob/master/limacharlie/__init__.py#L14

But it looks like that may not be the issue from your troubleshooting above.

When you did the login, you used the default environment correct? Not a named environment? If not, you need to specify the environment name when instantiating the Manager, or use `LC_CURRENT_ENV` to set it in the environment: https://github.com/refractionPOINT/python-limacharlie/blob/master/limacharlie/__init__.py#L48

**Comment by maximelb** [comment]
Reading in more details your report some more.
When you "use"d the environment, did you do it with the right shell execution notation? Like `. <(limacharlie use dev-org)`
You can check by looking in your environment (just run `env`) to see if the `LC_*` variables have been set. Not setting the environment or a typo in an environment could result in the above error.

**Comment by priamai** [comment]
I think I did, this is the file content:

```
env:
  nanocyber:
    api_key: 0fbe5b62-d1b0-43b3-b234-xxxxxx
    oid: 467ba90e-4254-4359-8c97-7e8426c7efb3
    uid: DDuwsT0SnDfrigiEXfhApmZZz6P2
```

Let me know if it looks well formed.

**Comment by dzimine-lc** [comment]
reopen if happens again
