### ISSUE TITLE
LimaCharlie Manager and User API Keys

### ISSUE THREAD

**Issue by priamai** [refractionPOINT/python-limacharlie#31]
## Expected Behavior

I want to list all the orgs that belong to my user via the user API key.

```
man = limacharlie.Manager(oid=A_OID,secret_api_key=USER_KEY)

orgs = man.userAccessibleOrgs()

for org in orgs:
    print(org)
```

## Actual Behavior

I am getting a:

`HTTP Error 401: Unauthorized`

## Steps to Reproduce the Problem

  1. Generate User API KEY
  2. Use LimaCharlie Manager

## Specifications

  - Version: Python3
  - Platform: Linux
  - Subsystem: Ubuntu
  -

**Comment by priamai** [comment]
Even if I just instantiate the manager:

`man = limacharlie.Manager(oid=A_OID,secret_api_key=USER_KEY)`

it gives me the error: HTTP Error 401: Unauthorized

**Comment by priamai** [comment]
I have generated the USER_KEY via the `https://app.limacharlie.io/profile` dashboard.

**Comment by maximelb** [comment]
You need to provide to the Manager the `uid`. See this example:
```
import limacharlie
lc = limacharlie.Manager( None, secret_api_key = 'MY_KEY', uid = 'MY_UID' )
lc.userAccessibleOrgs()
```

The UID is accessible from the same Profile page you generated the User API Key on.

**Comment by priamai** [comment]
Hmm is not working for me, did you made some changes to the package?

My attempt:
```

import limacharlie
import os
from pathlib import Path

USER_KEY='xxxx'
A_OID='yyyy'
UID = 'zzzzz'

print('Creating manager')
# Create an instance of the SDK.
man = limacharlie.Manager(None,uid=UID,secret_api_key=USER_KEY)

print('Getting accessible orgs')
orgs = man.userAccessibleOrgs()

for org in orgs:
    print(org)

print('Getting API keys')
api_keys = man.getApiKeys()
```
This is the error:

`orgs = man.userAccessibleOrgs()
  File "/home/ava/.local/share/virtualenvs/ava-glJNHu3-/lib/python3.8/site-packages/limacharlie/Manager.py", line 345, in userAccessibleOrgs
    resp = self._apiCall( '/user_key_info', POST, {}, queryParams = {
  File "/home/ava/.local/share/virtualenvs/ava-glJNHu3-/lib/python3.8/site-packages/limacharlie/Manager.py", line 248, in _apiCall
    raise LcApiException( 'Api failure (%s): %s' % ( code, str( data ) ) )
limacharlie.utils.LcApiException: Api failure (431): b''`

I have sent you the real keys in private to debug.
